[package]
name = "skulpin"
version = "0.1.2"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"
description = "This crate provides an easy option for drawing hardware-accelerated 2D by combining Vulkan and Skia."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aclysma/skulpin"
homepage = "https://github.com/aclysma/skulpin"
keywords = ["skia", "vulkan", "ash", "2d", "graphics"]
categories = ["graphics", "gui", "multimedia", "rendering", "visualization"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "shaders/*.frag",
    "shaders/*.vert",
    "shaders/*.spv",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "README.md"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.20.0-alpha4"
raw-window-handle = "0.3"
ash = "0.29"
skia-safe = { version = "0.17", features = ["vulkan"] }

log="0.4"

num-traits = "0.2"
num-derive = "0.2"
strum = "0.15"
strum_macros = "0.15"

# From ash example code
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["windef", "winuser"] }

[target.'cfg(target_os = "macos")'.dependencies]
metal-rs = "0.6"
cocoa = "0.13"
objc = ">=0.2,<0.2.7"

[dev-dependencies]
env_logger = "0.6"
